### ISSUE TITLE
readme file to be a bit clearer

### ISSUE THREAD

**Issue by stalvik** [WiringPi/WiringPi2-Python#8]
in the readme file, where it says `wiringpi2.pinMode(1,1) // Set pin 1 to output `
using another example would be a lot clearer eg:
`wiringpi2.pinMode(17,1) // Set pin 17 to output`
it's quite confusing when bothe the numbers are 1 and there is no real explanation to which is which.

**Comment by Gadgetoid** [comment]
This has been fixed, along with using the correct comment syntax for Python. Thanks!
